### ISSUE TITLE
Ditch atom4R dependency

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/deposits#12]
That package is unforunately insufficiently well maintained to be usable in an ongong form. The core functionality currently encapsulated by that package will have to be internally reconstructed here, which is mostly a translation of [Dublic Core Metadata terms](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/) into an R6 structure.

**Comment by mpadge** [comment]
Yep, I use explicit namespaces on all calls - search for `atom4R::` and you'll see them. There are only 2 instances of `atom4R::DCEntry$new()`, and everything else uses those objects without any need for further namespacing. Currently solution is
https://github.com/ropenscilabs/deposits/blob/0b1586234e196ceba9ca1fe0580ef6260540fb21/R/zzz.R#L2-L7 but that's not a long-term solution.

**Comment by eblondel** [comment]
I see, but is there any reason to stick with these explicit namespaces? I know it's good practice to avoid importing too much stuff on namespace and only those used by a r package (and go more for importFrom than import), but in that case you say that atom4R is supposed to be the 'backend' model in deposits, so why not importing it then? It's not a "big" package.

**Comment by mpadge** [comment]
None of that is relevant to https://github.com/eblondel/atom4R/issues/9. There are multiple ways to import functions, and explicit namespacing is functionally identical to `importFrom` statements. [Makes no difference](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Specifying-imports-and-exports) to either loading of packages, or the search path. To quote again from [same source there](https://r-pkgs.org/namespace.html#imports):

> Unless there is a strong reason not to, it’s better to be explicit. It’s a little more work to write, but a lot easier to read when you come back to the code in the future. The converse is not true.

And "better to be explicit" is referring directly to explicit namespacing like I use. So, yes, there's a very good reason. Importing a package a whole is not permitted.

**Comment by eblondel** [comment]
"Importing a package a whole is not permitted." that's not true, i'm sorry. If it would not be permitted, tons of packages would be removed from CRAN. :-) eg. https://github.com/rstudio/shiny/blob/main/NAMESPACE When import is justified, you can use it

**Comment by mpadge** [comment]
GitHub actions have been failing for days because of issues with XML which is depended on by {atom4R}. A very temporary solution is in https://github.com/ropenscilabs/deposits/commit/21151b78582ae584e5db75888383601e2e28f629 - but as stated in [r-lib/actions](https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies#installing-the-latest-dependencies), default binary installs should be very generally preferred because,

> This makes the jobs more robust, because installing source packages fails more often, especially on platforms without automatic system dependency installation (e.g. Windows and macOS).

Need to remove these `extra-packages` as soon as dependency on {atom4R} has been removed.

**Comment by eblondel** [comment]
@mpadge adding `any::XML` is not a temporary solution, it allows to make sure you rely on the latest XML package before all and not a deprecated version of the package. In your case you were relying on a old revision of XML. I believe you should get in touch with r-lib actions developers to better know how to deal with these issues.

This said I still don't get why you are pushing on getting atom4R if you don't want to use it. atom4R is actively maintained, used in **production** in national data portals (eg. Dataverse), accepted and published on CRAN, and used in other packages.

**Comment by mpadge** [comment]
@eblondel Thanks for your work on `atom4R` which has helped make the package more stable and usable. The `deposits` package will go forward using `atom4R` as a major dependency. The particular advantages of this are:

- Immediate access to the "namespace" of DCMI terms which will be updated whenever DCMI Standards are updated
- The `DCEntry$validate()` method offering single-line validation of DCMI objects (via `XML::xmlSchemaValidate`)

An example of a package which implements its own internal processing of DCMI terms is https://github.com/dataobservatory-eu/dataset/, which does neither of these, so is less robust  by definition and design, and also has to rely on an internally hard-coded [list of DCMI terms recognised by the package](https://github.com/dataobservatory-eu/dataset/blob/88c1d34ecd2f43a9673096c855c9e9ffd3cfb5f1/R/dublincore.R#L111-L124). The ease and robustness offered by `atom4R` are enough reason to keep using it here.
