### ISSUE TITLE
"deposit_publish" method

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/deposits#37]
Links to [zenodo](https://developers.zenodo.org/#deposition-actions) and [figshare](https://docs.figshare.com/#private_article_publish) "Publish" methods.

**Comment by noamross** [comment]
I imagine we want a UI method that interactively asks "are you sure?" when publishing, that can be overridden by a `DEPOSITS_ASK_PUBLISH` environment variable.

**Comment by mpadge** [comment]
Yes, this definitely won't just be a no-questions-asked process. I also intend to have some (likely default) option that merely opens the corresponding web page with the "Publish" button, which would at least be my preferred method.

**Comment by noamross** [comment]
These also need to include setting and changing the visibility level (such as embargo, requests for data, etc.)

**Comment by mpadge** [comment]
## Zenodo

- "publish" POST method, and Zenodo only has a single "state" variable, with values of "inprogress" for unpublished, and which is automatially change to "done" on publication. 

The metadata themselves then control access, via:
- "access_right" = ["open", "embargoed", "restricted", "closed"]
- "embargoed" requires specifying an "embargo_date", which will be automatically respected when the "publish" method is called.
- "restricted" requires specifying "access_conditions" as a free-form text field.

So any pre-publish questions for Zenodo would then examine any values for those variables, and formulate appropriate questions.

## Figshare

Figshare has no direct metadata fields like Zenodo for access rights or conditions.  Instead it has an "embargo" PUT method which accepts a number of parameters. This formally puts an article under embargo, and conditions can be queries via corresponding "embargo" GET method. An embargoed article is not automatically published, and still requires explicitly calling the "publish" method.  Previously-embargoed articles will then not actually be published until the "embargo_date" date has expired. (There is also an "embargo" DELETE method.)

---

## Plan

- First implement an "embargo" method that does not publish a deposit (it merely populates metadata on Zenodo, and calls the "embargo" method on Figshare).
- Issue message at end of embargo call stating that article will still not be published unless "publish" method is explicitly called.
- On calling "publish" method:
    - If not "embargoed", then issue question whether embargoes should be applied?
    - If not, go straight to publish; alternatively, call "embargo" method instead.

The only aspect that will not cover will then be access conditions/restrictions for Zenodo. That can then be considered once those aspects have been implemented.

**Comment by mpadge** [comment]
Those commits implement the embargo method for both Figshare and Zenodo.

**Comment by mpadge** [comment]
And that is the publish method. Next commit will close by adding tests for embargo methods. Publish methods will not be tested.
