### ISSUE TITLE
CI Validation workflows - `deposits` level

### ISSUE THREAD

**Issue by noamross** [ropenscilabs/deposits#47]
- Validate and report errors in `deposits`/repository-level metadata to catch errors prior to upload

**Comment by noamross** [comment]
- [ ] Check in with Carl re: json-ld and codemeta applicability
- [ ] Keep the data needed to validate (enumerated types, etc) as extdata rather than hard coding

**Comment by mpadge** [comment]
This is all done now via #39 and associated PRs #51, #53, #54. See [example in #50](https://github.com/ropenscilabs/deposits/issues/50#issuecomment-1481347434) for the validation in action. Everything is in extdata JSON schemas, with no service-specific code involved in validation.
