### ISSUE TITLE
New Zenodo API?

### ISSUE THREAD

**Issue by rkrug** [ropenscilabs/deposits#92]
Does `deposits` support the new Zenodo API? When I try to deposit something on the sandbox I get the following error (valid API key - checked with curl):

```
r$> cli
<deposits client>
 deposits service : zenodo
           sandbox: TRUE
         url_base : https://sandbox.zenodo.org/api/
 Current deposits : <none>

   hostdata : <none>
   metadata : 8 terms (see 'metadata' element for details)

r$> cli$deposit_new ()
Error in `httr2::req_perform()`:
! HTTP 400 Bad Request.
Run `rlang::last_trace()` to see where the error occurred.

r$> rlang::last_trace(drop = FALSE)
<error/httr2_http_400>
Error in `httr2::req_perform()`:
! HTTP 400 Bad Request.
---
Backtrace:
    ▆
 1. └─cli$deposit_new()
 2.   └─httr2::req_perform(req)
 3.     └─httr2:::handle_resp(req, resp, error_call = error_call)
 4.       └─httr2:::resp_abort(resp, req, body, call = error_call)
 5.         └─rlang::abort(...)

r$>
```

If yes, I am happy to provide more details.

**Comment by mpadge** [comment]
Ha, yeah, right, i can also repeat that. This is not good!! Thanks for reporting, and that is one that I'll get onto straight away

**Comment by mpadge** [comment]
Thanks @rkrug, that was a fairly minor API change that was easy to update. A bigger issue now seems to be that the Zenodo sandbox no longer lists any deposits, neither directly on website or accessible from the API. That kind of destroys ability to play around with deposits using the sandbox. The URLs for newly-created sandbox deposits work as expected, but nothing appears on the "dashboard," or via `cli$deposits_list()`. Are you seeing the same?

**Comment by rkrug** [comment]
Thanks @mpadge. Very much appreciated.

I just made a test deposit on my sandbocx account, logged out, logged in again and saw it under my deposits as well as could find it when searching for my name (Rainer - see screenshot)

It is also on the dashboard (but I think it took a bit of time, if I remember correctly). All this on the website.

I tried it with the installed version, and updated from GitHub, and in both cases `cli$deposits_list()` returns nothing.

<img width="824" alt="Screenshot 2023-12-05 at 16 19 10" src="https://github.com/ropenscilabs/deposits/assets/487172/d1a1204c-56c3-436e-9177-03ec0983daeb">

**Comment by rkrug** [comment]
<img width="983" alt="Screenshot 2023-12-05 at 16 24 38" src="https://github.com/ropenscilabs/deposits/assets/487172/0e0dfbf8-5126-4f7a-ab71-40b24e118765">

**Comment by rkrug** [comment]
Actually - I now see the following:

```
r$> cli
<deposits client>
 deposits service : zenodo
           sandbox: TRUE
         url_base : https://sandbox.zenodo.org/api/
 Current deposits : 1 (see 'deposits' element for details)

   hostdata : <none>
   metadata : 8 terms (see 'metadata' element for details)
```

so it is working - but the curious thing is it does not seem to be showing web interface deposits via the API, nor API deposits via the web interface. Orr am I to impatient again?

**Comment by mpadge** [comment]
Very strange. I still see absolutely nothing at all either way. And the numbers have changed from what used to be a generally 7-digit field to only 4, suggesting they are now recycling those much quicker. That suggests to me that sandbox deposits no longer have the semi-permanence they once did, and in my case appear to have none at all.

**Comment by rkrug** [comment]
I am also confused - I created a cli, populated the metadata, and want to upload a file:

```
r$> cli$deposit_upload_file('/Users/rainerkrug/Documents_Local/git/LEEF/additionalPackages/zenDep/inst/leef.rrd.v1.8.5_fin
    al.density.sqlite.gz')
Error in cli$deposit_upload_file("/Users/rainerkrug/Documents_Local/git/LEEF/additionalPackages/zenDep/inst/leef.rrd.v1.8.5_final.density.sqlite.gz") : 
  Assertion on 'deposit_id' failed: Must be of type 'single integerish value', not 'NULL'.
```

I was sure it worked before...

**Comment by mpadge** [comment]
Yeah, this is going to be a problem. The `deposit_id` value should be populated from the Zenodo sandbox data, but if that's all empty, there's no value to use. I'll address your other issues first, but feel free to open a new issue regarding that if it persists. Thanks

**Comment by rkrug** [comment]
Hm. I get the same error again:

```
r$> cli
<deposits client>
 deposits service : zenodo
           sandbox: FALSE
         url_base : https://zenodo.org/api/
 Current deposits : 28 (see 'deposits' element for details)

   hostdata : <none>
   metadata : 8 terms (see 'metadata' element for details)

r$> cli$deposit_new()
Error in `httr2::req_perform()`:
! HTTP 400 Bad Request.
Run `rlang::last_trace()` to see where the error occurred.

r$> packageVersion("deposits")
[1] ‘0.2.1.52’

r$>
```

**Comment by rkrug** [comment]
Also tried on the sandbox - same error.

**Comment by rkrug** [comment]
I am checking - your example works. I will report back.
